version: '3.8'

services:
  # Redis Cluster Nodes
  redis-cluster-1:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}  --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-cluster-1-data:/data
    networks:
      redis-net:
        aliases:
          - redis1
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis-cluster-2:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - '${REDIS2_PORT}:6379'
    volumes:
      - redis-cluster-2-data:/data
    networks:
      redis-net:
        aliases:
          - redis2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis-cluster-3:
    image: redis:latest
    command: redis-server  --requirepass ${REDIS_PASSWORD} --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - '${REDIS3_PORT}:6379'
    volumes:
      - redis-cluster-3-data:/data
    networks:
      redis-net:
        aliases:
          - redis3
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Redis Cluster Initializer
  redis-cluster-init:
    image: redis:latest
    depends_on:
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3
    command: >
       bash -c "
         export REDISCLI_AUTH=${REDIS_PASSWORD} &&
         sleep 5 &&
         echo 'yes' | redis-cli --cluster create redis1:6379 redis2:6379 redis3:6379 --cluster-replicas 0"
    networks:
      - redis-net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Bull Queue Redis
  redis-bull:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - '${BULL_PORT}:6400'
    volumes:
      - redis-bull-data:/data
    networks:
      redis-net:

  # MySQL Service
  mysql:
   image: mysql:latest
   ports:
     - "${DB_PORT}:3306"
   environment:
     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  redis-net:
    driver: bridge

volumes:
  redis-cluster-1-data:
  redis-cluster-2-data:
  redis-cluster-3-data:
  redis-bull-data:
