version: '3.8'

services:
  redis-node-1:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - '6379:6379'
      - '16379:16379'
    volumes:
      - redis-node-1-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.2

  redis-node-2:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - '6380:6379'
      - '16380:16379'
    volumes:
      - redis-node-2-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.3

  redis-node-3:
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - '6381:6379'
      - '16381:16379'
    volumes:
      - redis-node-3-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.4

networks:
  redis-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
