version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data # 별도 볼륨 사용
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    restart: always
    networks:
      - multipleRoguelike

  mysql:
    image: mysql:latest
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql # 별도 볼륨 사용
    networks:
      - multipleRoguelike

networks:
  multipleRoguelike:

volumes:
  redis-data: # Redis 데이터를 저장할 볼륨
  mysql-data: # MySQL 데이터를 저장할 볼륨
